### ISSUE TITLE
generatorConfig.vm 这个文件是什么，怎么找不到！

### ISSUE THREAD

**Issue by shf4715** [shuzheng/zheng#40]
运行CMS-Dao 中的Generator.main产生的错误。

释放数据库连接
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'generatorConfig.vm'
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
	at org.apache.velocity.runtime.RuntimeSingleton.getTemplate(RuntimeSingleton.java:317)
	at org.apache.velocity.app.Velocity.getTemplate(Velocity.java:378)
	at com.zheng.common.util.VelocityUtil.generate(VelocityUtil.java:32)
	at com.zheng.common.util.MybatisGeneratorUtil.generator(MybatisGeneratorUtil.java:89)
	at com.zheng.cms.dao.Generator.main(Generator.java:38)
========== 结束生成generatorConfig.xml文件 ==========
========== 开始运行MybatisGenerator ==========
Exception in thread "main" java.io.FileNotFoundException: zheng-cms/zheng-cms-dao/src/main/resources/generatorConfig.xml (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at org.mybatis.generator.config.xml.ConfigurationParser.parseConfiguration(ConfigurationParser.java:103)
	at com.zheng.common.util.MybatisGeneratorUtil.generator(MybatisGeneratorUtil.java:103)
	at com.zheng.cms.dao.Generator.main(Generator.java:38)

**Comment by jinxintang** [comment]
generatorConfig.vm是用于生成generatorConfig.xml的模板，而generatorConfig.xml是mybatis生成器用于生成mapper类，映射文件，pojo的配置文件。

**Comment by shuzheng** [comment]
可能是在eclipse下相对路径获取模板有问题，一直也没有测试eclipse，欢迎fix bug

**Comment by xjh1994** [comment]
@shuzheng Mac下路径有问题，需要把 `MybatisGeneratorUtil.java` 的几个` replaceFirst("/", "")` 去掉
