### ISSUE TITLE
zheng-upms-rpc-service 启动报 zkclient.exception.ZkException: Unable to connect to zkserver:2181

### ISSUE THREAD

**Issue by qinchz** [shuzheng/zheng#92]
zheng大大以及各位大佬好，请教一个问题。
zheng-upms-rpc-service启动报如下的错误，跑rpc-serve之前，启动了zkServer.cmd。
交换了两者的启动顺序还是不行，不知道什么原因。

环境：Win10、jdk1.8.0_144、ideaIU-2017.2.5.win、zookeeper-3.5.2-alpha

2017-10-27 13:33:28,065 [ZkClient-EventThread-38-zkserver:2181] INFO  [org.I0Itec.zkclient.ZkEventThread] - Terminate ZkClient event thread.
**Exception in thread "main" org.I0Itec.zkclient.exception.ZkException: Unable to connect to zkserver:2181**
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:66)
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:872)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:92)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:76)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:72)
	at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperClient.<init>(ZkclientZookeeperClient.java:25)
	at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperTransporter.connect(ZkclientZookeeperTransporter.java:10)
	at com.alibaba.dubbo.remoting.zookeeper.ZookeeperTransporter$Adaptive.connect(ZookeeperTransporter$Adaptive.java)
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.<init>(ZookeeperRegistry.java:69)
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistryFactory.createRegistry(ZookeeperRegistryFactory.java:37)
	at com.alibaba.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:95)
	at com.alibaba.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:201)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:118)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:92)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:54)
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:550)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:346)
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:307)
	at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:206)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:109)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.zheng.upms.rpc.ZhengUpmsRpcServiceApplication.main(ZhengUpmsRpcServiceApplication.java:17)
**Caused by: java.net.UnknownHostException: zkserver**
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.zookeeper.ClientCnxn.<init>(ClientCnxn.java:386)
	at org.apache.zookeeper.ClientCnxn.<init>(ClientCnxn.java:331)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:377)
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:64)
	... 31 more

![image](https://user-images.githubusercontent.com/18414101/32089744-62c82f9c-bb1e-11e7-8e4d-107de7fe84d5.png)

**Comment by qinchz** [comment]
1、修改了applicationContext-dubbo-provider.xml文件中的   zkServer为localhost
 <dubbo:registry address="zookeeper://localhost:2181"/>
2、先启动rpc-server，后启动zkServer
